export const INVOICE_FIELDS_LABEL_MAP = {
  'accountingCode': 'ui-invoice.invoice.accountingCode',
  'acqUnitIds[\\d]': 'ui-invoice.invoice.details.information.acqUnits',
  'adjustments[\\d].description': 'ui-invoice.settings.adjustments.description',
  'adjustments[\\d].exportToAccounting': 'ui-invoice.settings.adjustments.exportToAccounting',
  'adjustments[\\d].prorate': 'ui-invoice.settings.adjustments.prorate',
  'adjustments[\\d].relationToTotal': 'ui-invoice.settings.adjustments.relationToTotal',
  'adjustments[\\d].type': 'ui-invoice.settings.adjustments.type',
  'adjustments[\\d].value': 'ui-invoice.settings.adjustments.value',
  'adjustments[\\d].id': 'ui-invoice.invoice.details.lines.list.adjustments',
  'adjustmentsTotal': 'ui-invoice.invoice.details.information.adjustment',
  'approvalDate': 'ui-invoice.invoice.approvalDate',
  'approvedBy': 'ui-invoice.invoice.approvedBy',
  'batchGroupId': 'ui-invoice.invoice.details.information.batchGroup',
  'billTo': 'ui-invoice.invoice.billTo',
  'cancellationNote': 'ui-invoice.invoice.cancellationNote',
  'chkSubscriptionOverlap': 'ui-invoice.invoice.chkSubscriptionOverlap',
  'currency': 'ui-invoice.invoice.currency',
  'enclosureNeeded': 'ui-invoice.invoice.enclosureNeeded',
  'exchangeRate': 'ui-invoice.invoice.details.voucher.exchangeRate',
  'exportToAccounting': 'ui-invoice.invoice.exportToAccounting',
  'fiscalYearId': 'ui-invoice.invoice.details.information.fiscalYear',
  'folioInvoiceNo': 'ui-invoice.invoice.folioInvoiceNo',
  'invoiceDate': 'ui-invoice.invoice.details.information.invoiceDate',
  'lockTotal': 'ui-invoice.invoice.lockTotal',
  'note': 'ui-invoice.invoice.note',
  'paymentDate': 'ui-invoice.invoice.paymentDate',
  'paymentDue': 'ui-invoice.invoice.details.information.paymentDue',
  'paymentMethod': 'ui-invoice.invoice.paymentMethod',
  'paymentTerms': 'ui-invoice.invoice.paymentTerms',
  'poNumbers[\\d]': 'ui-invoice.search.poNumbers',
  'source': 'ui-invoice.invoice.details.information.source',
  'status': 'ui-invoice.invoice.details.information.status',
  'subTotal': 'ui-invoice.invoice.details.information.subTotal',
  'total': 'ui-invoice.invoice.details.information.calculatedTotalAmount',
  'vendorInvoiceNo': 'ui-invoice.invoice.vendorInvoiceNo',
  'voucherNumber': 'ui-invoice.invoice.voucherNumber',
};

export const HIDDEN_INVOICE_FIELDS = [
  'nextInvoiceLineNumber',
];
