export const EXPORT_INVOICE_FIELDS = {
  vendorInvoiceNo: 'Vendor invoice number',
  vendorCode: 'Vendor code',
  status: 'Status',
  invoiceDate: 'Invoice date',
  fiscalYear: 'Fiscal year',
  paymentDue: 'Payment due',
  approvalDate: 'Approved date',
  approvedBy: 'ApprovedBy',
  paymentTerms: 'Terms',
  acqUnitIds: 'Acquisitions units',
  note: 'Note',
  billTo: 'Bill to',
  batchGroup: 'Batch group',
  paymentDate: 'Payment date',
  totalUnits: 'Total units',
  subTotal: 'Sub total',
  adjustmentsTotal: 'Total adjustments',
  totalAmount: 'Total amount',
  lockTotal: 'Lock total amount',
  invoiceFundDistributions: 'Invoice fund distributions',
  invoiceAdjustments: 'Invoice adjustments',
  accountingCode: 'Accounting code',
  vendorAddress: 'Vendor address',
  paymentMethod: 'Payment method',
  chkSubscriptionOverlap: 'Check subscription overlap',
  exportToAccounting: 'Export to accounting',
  enclosureNeeded: 'Enclosure needed',
  currency: 'Currency',
  exchangeRate: 'Exchange rate',
  invoiceTags: 'Invoice tags',
  createdBy: 'Created by',
  dateCreated: 'Date created',
  updatedBy: 'Updated by',
  dateUpdated: 'Date updated',
};

export const EXPORT_INVOICE_LINE_FIELDS = {
  invoiceLineNumber: 'Invoice line number',
  description: 'Description (Title)',
  poLineNumber: 'POLine number',
  subscriptionInfo: 'Subscription info',
  subscriptionStart: 'Subscription start',
  subscriptionEnd: 'Subscription end',
  comment: 'Comment',
  accountNumber: 'Account number',
  lineAccountingCode: 'Accounting code',
  quantity: 'Quantity',
  lineSubTotal: 'Sub total',
  lineAdjustments: 'Invoice line adjustments',
  total: 'Total',
  lineFundDistributions: 'Invoice line fund distributions',
  externalAccountNumber: 'External account number',
  referenceNumbers: 'Vendor reference number, reference type',
  lineTags: 'Invoice line tags',
  voucherNumber: 'Voucher number',
  voucherStatus: 'Voucher status',
  voucherDate: 'Voucher date',
  disbursementNumber: 'Disbursement number',
  disbursementDate: 'Disbursement date',
  invoiceLineCreatedBy: 'Created by (Invoice Line)',
  invoiceLineDateCreated: 'Date created (Invoice Line)',
  invoiceLineUpdatedBy: 'Updated by (Invoice Line)',
  invoiceLineDateUpdated: 'Date updated (Invoice Line)',
};

export const EXPORT_INVOICE_FIELDS_OPTIONS = Object.keys(EXPORT_INVOICE_FIELDS).map(field => ({
  label: EXPORT_INVOICE_FIELDS[field],
  value: field,
}));

export const EXPORT_INVOICE_LINE_FIELDS_OPTIONS = Object.keys(EXPORT_INVOICE_LINE_FIELDS).map(field => ({
  label: EXPORT_INVOICE_LINE_FIELDS[field],
  value: field,
}));
