export const FILTERS = {
  PAYMENT_METHOD: 'paymentMethod',
  STATUS: 'status',
  VENDOR: 'vendorId',
  DATE_CREATED: 'metadata.createdDate',
  INVOICE_DATE: 'invoiceDate',
  PAYMENT_DATE: 'paymentDate',
  PAYMENT_DUE: 'paymentDue',
  APPROVAL_DATE: 'approvalDate',
  SOURCE: 'source',
  EXPORT_TO_ACCOUNTING: 'exportToAccounting',
  ACQUISITIONS_UNIT: 'acqUnitIds',
  TAGS: 'tags.tagList',
  BATCH_GROUP: 'batchGroupId',
  EXPENSE_CLASS: 'expenseClass',
  FUND_CODE: 'fundCode',
  LOCK_TOTAL: 'lockTotal',
  FISCAL_YEAR: 'fiscalYearId',
};
